// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuzKRdMeHDIfE8mVLG4M4NnGIDtR25hM8',
    appId: '1:967634825333:web:9e941dc64427f88c9b483c',
    messagingSenderId: '967634825333',
    projectId: 'reverie-9ea2e',
    authDomain: 'reverie-9ea2e.firebaseapp.com',
    storageBucket: 'reverie-9ea2e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBNSlJZnoV2pvF-YGy7WE7oaHXHPIOzx0',
    appId: '1:967634825333:android:4e92fa87d53177079b483c',
    messagingSenderId: '967634825333',
    projectId: 'reverie-9ea2e',
    storageBucket: 'reverie-9ea2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBChDleQ-P_r34Tp7kFi46IiwQLFYeUW04',
    appId: '1:967634825333:ios:84c26736ea3db8b59b483c',
    messagingSenderId: '967634825333',
    projectId: 'reverie-9ea2e',
    storageBucket: 'reverie-9ea2e.firebasestorage.app',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBChDleQ-P_r34Tp7kFi46IiwQLFYeUW04',
    appId: '1:967634825333:ios:84c26736ea3db8b59b483c',
    messagingSenderId: '967634825333',
    projectId: 'reverie-9ea2e',
    storageBucket: 'reverie-9ea2e.firebasestorage.app',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuzKRdMeHDIfE8mVLG4M4NnGIDtR25hM8',
    appId: '1:967634825333:web:925eaf453c7ad6f39b483c',
    messagingSenderId: '967634825333',
    projectId: 'reverie-9ea2e',
    authDomain: 'reverie-9ea2e.firebaseapp.com',
    storageBucket: 'reverie-9ea2e.firebasestorage.app',
  );
}
